/**
 * fal-inpainting.ts
 *
 * Companion to fal-provider.ts for the localised material-edit
 * workflow (Sprint F / Munkacsomag 3). Lives in its own module
 * because the inpainting call shape is meaningfully different from
 * the Canny ControlNet realism pass — different model, different
 * inputs, different defaults — and forcing them into one provider
 * adapter would muddy both code paths.
 *
 * The contract is plain: hand over the source image bytes, a binary
 * PNG mask (white = "regenerate this pixel", black = "leave alone"),
 * a free-text prompt and an optional strength slider. We upload both
 * to Fal storage, call the configured Flux Fill / inpainting model,
 * download the result, and hand it back to the caller. The caller is
 * responsible for the final composite (outside-mask must be pixel-
 * perfect identical to the source; this module trusts the model
 * insofar as it does for the inside-mask region).
 */

import path from "path";

import { fal } from "@fal-ai/client";

const DEFAULT_MODEL = process.env.FAL_INPAINTING_MODEL ?? "fal-ai/flux-pro/v1/fill";
const DEFAULT_INFERENCE_STEPS = Number(
  process.env.FAL_INPAINTING_INFERENCE_STEPS ?? "28"
);
const DEFAULT_GUIDANCE_SCALE = Number(
  process.env.FAL_INPAINTING_GUIDANCE_SCALE ?? "30"
);

let configured = false;

function ensureConfigured(): void {
  if (configured) return;
  const key = process.env.FAL_KEY;
  if (!key) {
    throw new Error(
      "Missing FAL_KEY environment variable. Set FAL_KEY in .env to use the Fal.ai provider."
    );
  }
  fal.config({ credentials: key });
  configured = true;
}

export type InpaintInput = {
  /** Absolute path to the source image on disk. */
  sourcePath: string;
  /** Pre-read source bytes (saves a re-read by the caller). */
  sourceBytes: Buffer;
  /**
   * Binary PNG mask, same pixel dimensions as the source. White
   * pixels mark the area to regenerate; black pixels must be
   * preserved by the model.
   */
  maskBytes: Buffer;
  /** Free-text material/colour directive supplied by the user. */
  prompt: string;
  /**
   * Optional 0..1 denoising strength. Only honoured by models that
   * expose it (flux/dev/inpainting); flux-pro/v1/fill ignores it.
   */
  strength?: number;
};

export type InpaintResult = {
  /** The Fal-generated bytes (typically JPEG). May still need to be
   *  composited over the source by the caller to guarantee
   *  outside-mask pixel preservation. */
  generatedBytes: Buffer;
  metadata: {
    model: string;
    promptUsed: string;
    inferenceSteps: number;
    guidanceScale: number;
    strength?: number;
    sourceUrl: string;
    maskUrl: string;
    generatedUrl: string;
    requestId?: string;
    seed?: number;
    timings?: Record<string, number> | null;
  };
};

type FalSubscribeResponse = {
  data?: {
    images?: Array<{ url: string; width?: number; height?: number; content_type?: string }>;
    image?: { url: string };
    seed?: number;
    timings?: Record<string, number>;
  };
  requestId?: string;
};

function pickImageUrl(response: FalSubscribeResponse): string | undefined {
  return response.data?.images?.[0]?.url ?? response.data?.image?.url;
}

/**
 * Run the configured Fal Fill / inpainting model on a (source, mask,
 * prompt) tuple and return the raw model output. The caller composites.
 */
export async function inpaintWithFal(input: InpaintInput): Promise<InpaintResult> {
  ensureConfigured();

  const sourceExt = path.extname(input.sourcePath).toLowerCase();
  const sourceMime =
    sourceExt === ".jpg" || sourceExt === ".jpeg"
      ? "image/jpeg"
      : sourceExt === ".webp"
        ? "image/webp"
        : "image/png";

  // Upload source + mask to Fal storage so the model can fetch them
  // by URL. (Flux Fill rejects data URIs, just like the realism pass —
  // see debug_report.md K2.)
  const [sourceUrl, maskUrl] = await Promise.all([
    fal.storage.upload(
      new File([new Uint8Array(input.sourceBytes)], path.basename(input.sourcePath), {
        type: sourceMime,
      })
    ),
    fal.storage.upload(
      new File([new Uint8Array(input.maskBytes)], "mask.png", { type: "image/png" })
    ),
  ]);

  // Build the model input. flux-pro/v1/fill takes image_url +
  // mask_url + prompt. flux/dev/inpainting also accepts strength.
  // We pass strength only when set, so the Pro endpoint doesn't
  // 422 on an unknown field.
  const modelInput: Record<string, unknown> = {
    prompt: input.prompt,
    image_url: sourceUrl,
    mask_url: maskUrl,
    num_inference_steps: DEFAULT_INFERENCE_STEPS,
    guidance_scale: DEFAULT_GUIDANCE_SCALE,
    num_images: 1,
    enable_safety_checker: false,
    output_format: "jpeg",
  };
  if (typeof input.strength === "number") {
    modelInput.strength = input.strength;
  }

  const result = (await fal.subscribe(DEFAULT_MODEL, {
    input: modelInput,
    logs: false,
  })) as FalSubscribeResponse;

  const generatedUrl = pickImageUrl(result);
  if (!generatedUrl) {
    throw new Error(
      `Fal.ai (${DEFAULT_MODEL}) returned no image. Raw: ${JSON.stringify(result).slice(0, 300)}`
    );
  }

  const downloadResponse = await fetch(generatedUrl);
  if (!downloadResponse.ok) {
    throw new Error(
      `Fal.ai download failed: ${downloadResponse.status} ${downloadResponse.statusText} (${generatedUrl})`
    );
  }
  const generatedBytes = Buffer.from(await downloadResponse.arrayBuffer());

  return {
    generatedBytes,
    metadata: {
      model: DEFAULT_MODEL,
      promptUsed: input.prompt,
      inferenceSteps: DEFAULT_INFERENCE_STEPS,
      guidanceScale: DEFAULT_GUIDANCE_SCALE,
      strength: input.strength,
      sourceUrl,
      maskUrl,
      generatedUrl,
      requestId: result.requestId ?? undefined,
      seed: result.data?.seed,
      timings: result.data?.timings ?? null,
    },
  };
}
